sudo: required

services:
  - docker

install: true

before_script:
#  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
#  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register

env:
  - DISTRO=jessie
  - DISTRO=latest

script:
  # Run shellcheck on branch
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git clone https://github.com/tomeshnet/prototype-cjdns-pi.git
  - cd prototype-cjdns-pi/scripts
  - git checkout ${BRANCH}
  - bash -c 'shopt -s globstar; shellcheck -x install install2 */install **/*.sh'
  - cd ../..

  ## Build docker for ARM tests
  #- cp /usr/bin/qemu-arm-static travis/${DISTRO}/
  #- docker build -t tomeshnet/prototype-cjdns-pi:${DISTRO} travis/${DISTRO}/


  ## Validate install script download and make executable
  #- docker run tomeshnet/prototype-cjdns-pi:${DISTRO} /bin/sh -c "wget https://raw.githubusercontent.com/tomeshnet/prototype-cjdns-pi/master/scripts/install; chmod +x install; UNATTENDED=true ./install"


# filename: preheat
#!/bin/sh

# Prep environment
- apt-get update
- apt-get install -y wget bash zip
- apt-get install -y qemu qemu-user-static binfmt-support
- apt-get install -y systemd-container


# Download if missing
- if [ ! -f "raspbian.zip" ]; then \
   wget https://downloads.raspberrypi.org/raspbian_lite_latest -O raspbian.zip \ 
fi
- if [ ! -f "2018-11-13-raspbian-stretch-lite.img" ]; then \
    unzip raspbian.zip \
 fi

# Grow image to make it a bit more space
- dd if=/dev/zero count=1000000 >> 2018-11-13-raspbian-stretch-lite.img

- echo -e "d\n2\nn\np\n2\n98304\n\n\nw\n" | fdisk 2018-11-13-raspbian-stretch-lite.img

- losetup /dev/loop99 2018-11-13-raspbian-stretch-lite.img -o $((512*98304))
- e2fsck -f -y /dev/loop99
- resize2fs /dev/loop99
- losetup -d  /dev/loop99

- mkdir 1
- mount 2018-11-13-raspbian-stretch-lite.img 1 -o loop,offset=$((512*98304))
- cd 1
- mount --bind /dev dev/
- mount --bind /sys sys/
- mount --bind /proc proc/
- mount --bind /dev/pts dev/pts
- cp /usr/bin/qemu-arm-static usr/bin


  # TODO Test installation
